# # _________________________________________
GET http://localhost:4000/wrpl-database/products?sellerid=user_2QcDEt57ix7kQuSL7Mchgtn1gqR
# page, name, maxPrice, minPrice, sellerid


# _________________________________________





# GET http://localhost:4000/wrpl-database/product/6474b2208bb22355a0bca1dd

# _________________________________________




# PUT http://localhost:4000/wrpl-database/admin/product/update/6474b2208bb22355a0bca1db
# Content-Type: application/json

# {
#     "ratings" : 5
# }


# _________________________________________


# DELETE http://localhost:4000/wrpl-database/admin/product/delete/6474b2208bb22355a0bca1db


# _________________________________________



# POST http://localhost:4000/wrpl-database/admin/product/add/
# Content-Type: application/json

# {
#     "name": "Tes Product",
#     "price": 87.511,
#     "desc": "The Radiant Raiment Jacket captures the essence of beauty, with its graceful silhouette and timeless appeal.",
#     "ratings" : 5,
#     "category": "Jackets/Coats",
#     "size": "XL",
#     "sellerid": "2007"
# }

